<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height

        padding: 30
        spacing: 20

        Button:
            text: "Hello World!"

        Button:
            text: "Goodby World!"
            pos_hint: {'center_x': 0.5}
            size_hint: (.3, 1)

        Button:
            text: "I'm  Hungry!!"
            pos_hint: {'center_x': 0.5}
            size_hint:(None, None)
            width: 100
            height: 50
