<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height

		Label:
		    markup: True
		    text: 'This is [color=#2CE144][b]Bold[/color] [font=times]Text[/font][/b] [sup]Up[/sup] and [sub]Down[/sub]'
		    font_size: 32

		Label:
		    markup: True
		    text: 'This is [size=100][i]Italics Text[/i][/size]'
		    font_size: 32

		Button:
		    markup: True
		    text: '[u]Click[/u] [s]Me![/s]'
		    font_size: 32
